export enum Category {
  BREAKFAST = 'BREAKFAST',
  LUNCH = 'LUNCH',
  DINNER = 'DINNER',
  DESSERT = 'DESSERT',
  APPETIZER = 'APPETIZER',
  SNACK = 'SNACK',
  DRINK = 'DRINK',
  SALAD = 'SALAD',
  SOUP = 'SOUP',
  SAUCE = 'SAUCE',
  SIDE_DISH = 'SIDE_DISH',
  BREAD = 'BREAD',
  PASTA = 'PASTA',
  MEAT = 'MEAT',
  OTHER = 'OTHER'
}
