export enum Unit {
  BOTTLE = 'Bottle',
  CAN = 'Can',
  CUP = 'Cup',
  DASH = 'Dash',
  DROP = 'Drop',
  GALLON = 'Gallon',
  GRAM = 'Gram',
  KILOGRAM = 'Kilogram',
  LITER = 'Liter',
  MILLILITER = 'Milliliter',
  OUNCE = 'Ounce',
  PINT = 'Pint',
  POUND = 'Pound',
  QUART = 'Quart',
  TABLESPOON = 'Tablespoon',
  TEASPOON = 'Teaspoon',
  COUNT = 'Count',
  PIECE = 'Piece',
  SLICE = 'Slice',
  HANDFUL = 'Handful'
}
